version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/chinmay/jellyfin/config:/config:Z
      - /home/chinmay/jellyfin/cache:/cache:Z
      - /home/chinmay/jellyfin/media:/media:Z
    restart: unless-stopped